### ISSUE TITLE
delete from cart not working as expected

### ISSUE THREAD

**Issue by shubhdo42** [shubhdo42/amazon-clone#1]
when you click on delete on cart it deletes the item on the first index and not the desired element in 

[https://github.com/shubhdo42/amazon-clone/blob/main/src/reducer.js](url)

**Comment by Ajinkya2000** [comment]
Let me check this.

**Comment by Ajinkya2000** [comment]
Try using a code formatter, it organizes your code.

**Comment by Ajinkya2000** [comment]
@shubhdo42 This is happening because you've not passed `id` as a prop in the Product Component, that's why `id` is undefined. In the `Home.js` component add an `id` to each product, and I think rest is fine.

I live this to you. Happy Coding!!

**Comment by shubhdo42** [comment]
working all good now
